from typing import Callable, TypeVar, Type, Union, Protocol

E = TypeVar("E")

class EventDispatcherProtocol(Protocol):
    def subscribe(self, event: Union[Type[E] | str], callback: Callable[[E], None]):...

    def unsubscribe(self, event: Union[Type[E] | str], callback: Callable[[E], None]):...

    def emit(self, event: E):...

    def emit_async(self, event: E):...